feat: 맥주 목록 조회 페이지 추가 (#69)
* feat: :sparkles: 맥주 정렬 선택 바텀싵 추가

* feat: :sparkles: 맥주 목록 페이지 필터, 정렬 결과 ui 추가

* feat: chip 디자인 수정

* fix: :bug: Hydration failed 에러 해결

Error: Hydration failed because the initial UI does not match what was rendered on the server.

https://stackoverflow.com/questions/71706064/react-18-hydration-failed-because-the-initial-ui-does-not-match-what-was-render

* feat: :lipstick: 화면 너비에 비례하는 크기에 대응

* feat: :lipstick: BeerItem rem 제거 및 반응형 대응

* chore: BeerLIst 간격 조정

* feat: 전체 버튼 제거 (SelectAllButton 제거)

* Revert "feat: :lipstick: 화면 너비에 비례하는 크기에 대응"

This reverts commit 8a65a158f140333ce1fb75882e64b910fe1330d1.

* feat: :lipstick: 화면 너비에 비례하는 크기에 대응

* feat: :sparkles: 맥주 목록 페이지 관련 api 추가

* refactor: :recycle: 변경된 맥주 데이터 구조 대응, type/beers.ts 제거

* refactor: :recycle: BeerList 리팩토링

* refactor: :recycle: rem -> px로 변환

* refactor: :recycle: hook default export로 수정

* chore: :lipstick: chip 폰트 수정

* fix: 맥주 api 응답 타입 수정

* chore: axiosClient 추가

* feat: :sparkles: 맥주 목록 페이지 전역 상태 추가

* feat: :heavy_plus_sign: react-query 설치 및 초기 설정

* feat: :sparkles: 맥주 검색 결과 없음 페이지 추가

* feat: :sparkles: BeerSearchResultList 추가

* feat: api 반환 값 수정

* feat: :sparkles: 맥주 필터 기능 구현

* feat: :sparkles: 바텀 네비게이션 추가

* chore: 바텀네비게이션 z-index:100,  position: sticky;

* fix: :rotating_light: lint 에러 수정

* refactor: :recycle: tabItem 상수로 선언

* chore: decodeURI 추가

* refactor: :recycle: useModal 함수 useCallback으로 감싸서 리팩토링

* Revert "fix: :bug: Hydration failed 에러 해결"

This reverts commit 3d415d603b063c4588b6e0c5af91dabe7a947378.

* fix: :bug: 머지하면서 발생한 type에러 수정

* fix: :bug: 자잘한 ui 버그 수정

* refactor: :recycle: 불필요한 async, await 제거